name: update cocomanhua keys

on:
  schedule:
    - cron: '0 0/8 * * *'
  workflow_dispatch:
  push:

jobs:
  updateKeys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            babel_asttools.js
          key: ${{ runner.os }}-autoCI-${{ hashFiles('**/README.md') }}
          restore-keys: |
            ${{ runner.os }}-autoCI-

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: autoBuild
          path: autoBuild

      - name: extra keys
        run: |
          bash $GITHUB_WORKSPACE/coco/coco.sh
          # mv result to autoBuild branch
          mv coco_keys.json ./autoBuild

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'update cocomanhua keys'
          branch: autoBuild
          repository: ./autoBuild
          file_pattern: coco_keys.json
          skip_checkout: false
          create_branch: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
